debug: true
log:
  level: info
http:
  port: 8002
  tls:
    enabled: false
grpc:
  port: 9002
  tls:
    enabled: false
store:
  postgres:
    url: postgres://admin:123456@127.0.0.1/maindb?sslmode=disable
    max_conns: 10
    max_conn_lifetime: 480
    max_conn_iddle_time: 380
    schema: migrations/postgres/schema.sql
  sqlite:
    address: "file::memory:?cache=shared"
    schema: migrations/sqlite/schema.sql
  dgraph:
    http: http://localhost:8080
    grpc: localhost:9080
  clickhouse:
    url: clickhouse://127.0.0.1:9000?dial_timeout=1s&compress=true
    max_conns: 11
    max_conn_lifetime: 480
    max_conn_iddle_time: 380
