debug: true
auth:
  disabled: false
  token_expiration: 900
log:
  level: info
  output: stdout
  format: text
http:
  port: 8001
  tls:
    enabled: false
    key: ../tls/server.key
    cert: ../tls/server.pem
grpc:
  port: 9001
  max_receive_msg_size: 5368709120 # 5MB
  tls:
    enabled: false
    key: ../tls/server.key
    cert: ../tls/server.pem
store:
  postgres:
    url: postgres://root:root@127.0.0.1/root?sslmode=disable
    max_conns: 500
    max_conn_lifetime: 480
    max_conn_iddle_time: 380
  sqlite:
    address: database.db
  dgraph:
    http: http://localhost:8080
    grpc: localhost:9080
