debug: true
auth:
  disabled: false
  token_expiration: 900
log:
  level: info
  output: stdout
  format: text
http:
  port: 8001
  tls:
    enabled: false
    key: ../tls/server.key
    cert: ../tls/server.pem
grpc:
  port: 9001
  max_receive_msg_size: 5368709120 # 5MB
  tls:
    enabled: false
    key: ../tls/server.key
    cert: ../tls/server.pem
store:
  postgres:
    url: postgres://admin:123456@127.0.0.1/maindb?sslmode=disable
    max_open_conns: 10
    max_iddle_cons: 10
    max_conn_lifetime: 480
  sqlite:
    address: database.db
  dgraph:
    http: http://localhost:8080
    grpc: localhost:9080
