debug: true
auth:
  disabled: false
  jwt:
    audience: web
    secret: mystrongpass
    expiration: 86400
    header: x-auth-token
    test:
      client_id: f7f4048b-58d6-4c1b-9c6a-41e96831c17a
      client_secret: 3hV5bwvcamCnqcCS239d2b83908d4373af829a0c27f34af0
      client_secret_hash: 2a1c0aac2bdfec1a6a8fc6712ff75450b30b22308fc6aa6b418aec6a0dc66ea22c9a8053bd975a990bbbabc2c910d86604dc47f3f3006f638a868618ff54a899$a14dc4033796c40440b7c7a8f73c00a5111d8efc78e109c1c1c55c1e6ba5c53e
log:
  level: info
http:
  port: 8002
  tls:
    enabled: false
grpc:
  port: 9002
  tls:
    enabled: false
store:
  postgres:
    url: postgres://admin:123456@127.0.0.1/maindb?sslmode=disable
    max_conns: 500
    max_conn_lifetime: 480
    max_conn_iddle_time: 380
    schema: migrations/postgres/schema.sql
  sqlite:
    address: "file::memory:?cache=shared"
    schema: migrations/sqlite/schema.sql
  dgraph:
    http: http://localhost:8080
    grpc: localhost:9080
